
services:
  chatbot:
    build:
      context: .
    env_file:
      - .env
    depends_on:
      - redis
    ports:
      - 3002:3002
    volumes:
      - ./logs:/app/logs

  redis:
    image: redis:latest
    ports:
      - "6379:6379"